### ISSUE TITLE
Julian dates don't care about timezone offsets?

### ISSUE THREAD

**Issue by ironwallaby** [ryanseys/lune#11]
https://github.com/ryanseys/lune/blob/master/lib/lune.js#L27

This strikes me as wrong. `Date.prototype.valueOf` is an alias to `Date.prototype.getDate`, which returns the number of milliseconds (ignoring leap seconds!) since 1 Jan 1970 UTC. This means that it's timezone offset is defined as zero: adding in my local timezone offset is mixing and matching values from two different timezones, which is asking for trouble: it will only work if your local timezone offset happens to be zero!

For comparison:

*   https://github.com/mourner/suncalc/blob/master/suncalc.js#L29
*   http://stackoverflow.com/questions/466321/convert-unix-timestamp-to-julian

As such, I believe this is a bug. (Also, `javascript.about.com` isn't a very reputable source :-1: )

**Comment by ironwallaby** [comment]
Furthermore, is there a reason why `Julian2Date` isn't simply the inverse operation of `getJulian`? A date object may simply be created using `new Date(milliseconds_since_epoch)`, so why go through all of the difficult effort of trying to parse out the years, months, days, hours, minutes, and seconds?

**Comment by ryanseys** [comment]
Sounds like you know a lot more than me! :) I would love if you summarized these thoughts into a PR so I can learn what I could have done to improve.

Thanks! :smile:

**Comment by ironwallaby** [comment]
Sounds good, will do. I think most of the issues I see stem from using `new Date(YY, MM, DD, HH, MM, SS)`, which is ambiguous (depending on where the host machine is!) and should never be used.

I'll try my hand and this and submit a PR as time permits :)

**Comment by ironwallaby** [comment]
Yup, there's definitely a bug here. I ported the accuracy test from the Python library, and average error dropped from 0.006219 to 0.000241!

I'm just wrapping up tests and other cleanup now, and will have a RP shortly.
