### ISSUE TITLE
Replace 'var' with 'let' and 'const'.

### ISSUE THREAD

**Issue by ironwallaby** [ryanseys/lune#13]
Creating this issue per prior discussion with @ryanseys; Lune is currently built to work with Node 0.10, but this restricts us to using ugly old `var`. For reasons of maintenance sanity, let's bring Lune up to date to work with the current LTS and Stable versions of Node, and make use of `let` and `const` while we're at it.

While I'm at it, any problems with my bringing in JSHint as a dev dependency and enabling some basic style checks?

**Comment by ryanseys** [comment]
@ironwallaby check #14 for style checks on testing run.

**Comment by ironwallaby** [comment]
I have a first pass at this complete in my fork: ironwallaby/lune

While going through, I found a bunch of dead code (branches that provably couldn't execute!), bad stylisms (capital letter non-constants!), and other oddities. Gonna do a quick check on them tomorrow and issue a PR.

**Comment by ryanseys** [comment]
Perfect, sounds great! I'm excited! ^_^
