### ISSUE TITLE
Moon phase: What value range approximates "full moon"?

### ISSUE THREAD

**Issue by owntheweb** [ryanseys/lune#20]
First, thank you for sharing this. AWESOME! I plan to share the little app I'm making that makes heavy use of this one as well.

My app will speak to the current phase of the moon approximately. It's approximate as I won't be able to know the user's timezone for now. With that in mind, what phase value range would approximate "full moon"?

If I have a phase value of 0.5 being a full moon and a lunar cycle of 29.5 days, I'm thinking:
0.5 +/- (1.0/29.5)
or:
0.4666 - 0.5334

Does that seem right? Am I in dangerous waters by not knowing the timezone of the app user?

Thanks for taking a look as I wrap my brain around this!

**Comment by ironwallaby** [comment]
By not knowing the timezone, you're adding a maximum of 12 hours of error, or 1.69%. On average, this means you can expect to mispredict a full moon every 4.77 years or so. This is probably okay, though I myself would try to remedy the error if at all possible—it's usually very easy to get one's timezone on any platform!

**Comment by owntheweb** [comment]
Aha! Thank you for your nearly instant feedback. This helps me out a lot.

I will definitely work to get the timezone adjustment in place. It's an Amazon Alexa Skill. At the moment I could have the skill ask for a timezone vocally or could request to link to the user's Amazon account. Both routes pose interesting challenges. I'll likely plan for an immediate update after my initial post (accuracy is good!).

Thanks again,

Chris

**Comment by ironwallaby** [comment]
No problem! I'm a little surprised—I would think the Alexa would already have some idea of the user's location. (Perhaps it's not exposed to developers for security reasons?)

But anyway, as mentioned above, defaulting to UTC shouldn't be too horrible. :)

Good luck!
