### ISSUE TITLE
Calculate lunar zodiac sign

### ISSUE THREAD

**Issue by g00dv1n** [ryanseys/lune#21]
Can I calculate lunar zodiac sign using your lib ?

http://www.lunarium.co.uk/moonsign/calculator.jsp

**Comment by ironwallaby** [comment]
No, `lune` is focused on calculating the moon's _phase_, and so the moon's zodiac sign is a bit out of scope for the project. Sorry!

(I bet you could reuse some of the project's math internals to compute it, but doing so would likely be tricky and you might be better served finding something dedicated to the purpose.)
