### ISSUE TITLE
Optimization Questions

### ISSUE THREAD

**Issue by ironwallaby** [ryanseys/lune#25]
I recently purchased a copy of [Astronomical Algorithms, 2nd ed.](https://www.amazon.com/Astronomical-Algorithms-Jean-Meeus/dp/0943396611) and was interested in implementing some of their approximation algorithms.

This is for two reasons: first, they're _much faster_, and second, they're _much simpler_. This can help with cases where high performance (e.g. getting a large number of lunar dates—which is my use-case 😉) is important, but mostly it's a benefit to maintainability.

I had two questions regarding this before I pass along a PR:

1.  What kind of accuracy guarantees does this library try to make? (If "none", then I should note my changes to `phase()` bring the amount of error in the moon phase from from 0.024% to 0.039%. The tests themselves check for an error of 0.1%, so we remain well below that threshold.)

2.  I'm seeing some issues in the tests, in particular these lines: https://github.com/ryanseys/lune/blame/9ffb65d76e9ed2c4334531601086edf516a8648e/test/index.js#L13-L14

    I can't tell whether the test is bad, or if my new calculations are, but I can't get the two to agree. I have checked and re-checked my code, though, and it seems to agree very well with all the other tests I can throw at it, so I suspect this test might be bad.

    Do you happen to remember where you got the data you're comparing against?

**Comment by ryanseys** [comment]
1) None

2) Test could be bad :) I forget the original source at this point.

**Comment by ironwallaby** [comment]
OK! Thanks. I'll have a PR together as time permits :)
