### ISSUE TITLE
How the calculation works?

### ISSUE THREAD

**Issue by PedroVinicius** [ryanseys/lune#8]
Good Work! Congratulations! :smiley: 

I need to make this same calculation in a Android App. You can explain me how this calculation works? I want to understand what is the theory from behind your code...

**Comment by ryanseys** [comment]
Hi I have ported my code from https://bazaar.launchpad.net/~keturn/py-moon-phase/trunk/annotate/head:/moon.py which explains a bit more where the theory comes from. Hope this helps!
